### ISSUE TITLE
default:cobble is converted to better_fences:wall_cobble

### ISSUE THREAD

**Issue by ghost** [ChimneySwift/better_fences#2]
When this mod loads any cobble in my inventory is converted to cobblestone wall. Digging stone drops cobblestone wall instead of cobble.

**Comment by LoneWolfHT** [comment]
I get this on Minetest 5.0 too @ChimneySwift

**Comment by ChimneySwift** [comment]
Woops, silly mistake, should be fixed in https://github.com/ChimneySwift/better_fences/commit/7c0109255846f4fc61ea3de419e3e506bbf1795f
